name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - main  # Változtasd meg a branch nevét, ha más a default

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build Docker image
      run: docker build -t bookDB_app .
      
    - name: Test Docker image
      run: docker run bookDB_app mvn test
      

